apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apsSecret.name }}
type: Opaque
stringData:
  {{ .Values.apsSecret.redisKey }}: "redis://redis:6379"
  {{ .Values.apsSecret.jwtKey }}: "supersecretjwt"
