replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/cloudopshub-das
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080   # typical API port

serviceAccount:
  create: false
  name: ""

dasSecret:
  name: das-secret
  dbKey: DATABASE_URL
  jwtKey: JWT_SECRET

resources: {}
probes:
  livenessPath: /health
  livenessInitialDelay: 10
  livenessPeriod: 20
  readinessPath: /ready
  readinessInitialDelay: 5
  readinessPeriod: 10
