apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dasSecret.name }}
type: Opaque
stringData:
  {{ .Values.dasSecret.dbKey }}: "postgres://user:password@postgres:5432/dasdb"
  {{ .Values.dasSecret.jwtKey }}: "supersecretjwt"
