replicaCount: 2

image:
  repository: 659591640509.dkr.ecr.us-west-2.amazonaws.com/cloudopshub-aps
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

serviceAccount:
  create: false
  name: ""

apsSecret:
  name: aps-secret
  redisKey: REDIS_URI
  jwtKey: JWT_SECRET

resources: {}
probes:
  livenessPath: /health
  livenessInitialDelay: 10
  livenessPeriod: 20
  readinessPath: /ready
  readinessInitialDelay: 5
  readinessPeriod: 10
